---
- hosts: all
  sudo: true
  roles:
    - role: megheaiulian.apache
      apache_vhost_default: false
      apache_vhosts:
        - name: "{{ project }}"
          path: /vagrant/web
          host: "{{ project }}.local"
    - role: megheaiulian.mysql
      mysql_databases:
        - name: "{{ project }}"
      mysql_users:
        - name: "{{ project }}"
          privs:
            - "{{ project }}.*:ALL"
          hosts:
            - localhost
    - role: megheaiulian.php
