---
- hosts: all
  become: true
  roles:
    - role: megheaiulian.apache
      apache_vhost_default: false
      apache_vhosts:
        - name: "{{ project }}"
          path: /vagrant/web
          host: "{{ project }}.local"
    - role: megheaiulian.mysql
      mysql_databases:
        - name: "{{ project }}"
          path: /vagrant/db/7.6.0-start.sql
      mysql_users:
        - name: "{{ project }}"
          privs:
            - "{{ project }}.*:ALL"
          hosts:
            - localhost
    - role: megheaiulian.php
      php_packages:
        - name: php
        - name: libapache2-mod-php7.0
      php_common_packages:
        - name: php-cgi
        - name: php-gd
        - name: php-curl
        - name: php-xml
        - name: php-mbstring
        - name: php-zip
      php_extra_packages:
        - name: php-mysql
  tasks:
    - name: install composer
      shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
      tags: composer

    - name: rename composer.phar to composer
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
      tags: composer

    - name: make composer executable
      file: path=/usr/local/bin/composer mode=a+x state=file
      tags: composer

    - name: install composer deps
      become: false
      composer: command=update working_dir=/vagrant prefer_dist=yes
